package com.expedia.www.hackathon.backpackersPool.controllers;


import com.expedia.www.hackathon.backpackersPool.models.Trip;
import com.expedia.www.hackathon.backpackersPool.repositories.TripRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Date;


@Controller    // This means that this class is a Controller
    @RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
    public class MainController {
        @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private TripRepository tripRepository;

        @GetMapping(path="/add") // Map ONLY GET Requests
        public @ResponseBody String addNewUser (@RequestParam String tid, @RequestParam String tud, @RequestParam String location, @RequestParam Date date, @RequestParam Boolean trekking, @RequestParam Boolean religious, @RequestParam Boolean localinteraction, @RequestParam Boolean sighseeing, @RequestParam Boolean nightlife, @RequestParam Integer language, @RequestParam Boolean smoking, @RequestParam Boolean sports, @RequestParam Integer age) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
          //  tid integer PRIMARY KEY , tuid integer , location varchar(100), time timestamp, trekking tinyint(1),religious tinyint(1), localinteraction tinyint(1), sightseeing tinyint(1) , nightlife tinyint(1),language_preffered tinyint(1), smoking_preffered tinyint(1), age_group tinyint(1))
            Trip trip=new Trip();
            trip.setAge(age);
            trip.setDate(date);
            trip.setLanguage(language);
            trip.setLocalInteraction(localinteraction);
            trip.setLocation(location);
            trip.setNightlife(nightlife);
            trip.setReligious(religious);
            trip.setSightseeing(sighseeing);
            trip.setSmoking(smoking);
            trip.setSports(sports);
            trip.setTid(Integer.parseInt(tid));
            trip.setTrekking(trekking);
            trip.setTuid(Integer.parseInt(tud));

            tripRepository.save(trip);
            return "Saved";
        }

        @GetMapping(path="/all")
        public @ResponseBody Iterable<Trip> getAllUsers() {
            // This returns a JSON or XML with the users
            return tripRepository.findAll();
        }


    }

